### ISSUE TITLE
Update operator install documentation

### ISSUE THREAD

**Issue by bettio** [astarte-platform/astarte-kubernetes-operator#145] opened 2020-07-29 10:03 UTC
kubectl -f apply is not enough anymore, update documentation making sure that prereqs are clear (e.g. make, helm, etc...).

**Comment by drf** [comment] 2020-07-31 10:11
This should migrate to the Helm chart (#147 ) when it's merged

**Comment by matt-mazzucato** [comment] 2020-12-23 09:45
Closing as the issue is fixed by [this](https://github.com/astarte-platform/astarte/pull/505) PR

**Closed by matt-mazzucato** 2020-12-23 09:45 UTC
Labels: blocking, documentation
